version: '3.8'

services:
  web:
    build: .
    image: hasan/node-postgres/1
    restart: "no"
    environment:
      DB_URI: "postgres://postgres:password@postgresql:5432/hasan-node-postgres-1"
    ports:
      - 8000:8000
    depends_on:
      - postgresql

  postgresql:
    build:
      context: .
      dockerfile: pg-Dockerfile
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hasan-node-postgres-1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresdb:/var/lib/postgresql/data/

volumes:
  postgresdb:
